#ifndef __BD_SYSCALL_NUMBERS__
#define __BD_SYSCALL_NUMBERS__

#define NR_LINUX_SCALABILITY	134
#define NR_THREADTEST			156
#define NR_COSTANT_OCCUPANCY	174
#define NR_CACHED_ALLOCATION	177
#define NR_BIMODAL				178

#endif
